#! /usr/bin/env bash

# Set up my OSX machine how I like it.

mv ~/Brewfile ~/.Brewfile.old
ln -s ~/Code/dotfiles/Brewfile ~/Brewfile

mv ~/.vimrc ~/.vimrc.old
ln -s ~/Code/dotfiles/vimrc ~/.vimrc

if ! [ -s ~/.config ]; then
	echo "creating config dir"
	mkdir -p ~/.config
fi

if ! [ -s ~/.config/nvim ]; then
	echo "creating nvim dir"
	mkdir -p ~/.config/nvim
fi

if ! [ -s ~/.config/nvim/init.lua ]; then
	echo "aliasing nvim init"
	ln -s ~/Code/dotfiles/nvim/init.lua ~/.config/nvim/init.lua
fi

mv ~/.zshrc ~/.zshrc.old
ln -s ~/Code/dotfiles/zshrc ~/.zshrc

mv ~/.tmux.conf ~/.tmux.conf.old
ln -s ~/Code/dotfiles/tmux.conf ~/.tmux.conf

mv ~/.asdfrc ~/.asdf.old
ln -s ~/Code/dotfiles/asdfrc ~/.asdfrc

mv ~/.tool-versions ~/.tool-versions.old
ln -s ~/Code/dotfiles/tool-versions ~/.tool-versions

# Install asdf plugins
asdf plugin add ruby
asdf plugin add nodejs
asdf plugin add rust

if ! [ -s ~/.gitconfig ]; then
    ln -s ~/Code/dotfiles/gitconfig ~/.gitconfig
fi

# Setup The Silver Searcher Ignore file
mv ~/.ignore ~/.ignore.old
ln -s ~/Code/dotfiles/.ignore ~/.ignore

if ! [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Skipping OSX-specific setup"
    exit 0
fi

# OSX key repeat settings
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15 

# Save screenshots to the Downloads folder
defaults write com.apple.screencapture location ~/Downloads
