set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'morhetz/gruvbox'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'mileszs/ack.vim'
Plugin 'janko-m/vim-test'
Plugin '907th/vim-auto-save'
Plugin 'vim-ruby/vim-ruby'
Plugin 'airblade/vim-gitgutter'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'Quramy/tsuquyomi'
Plugin 'dense-analysis/ale'

call vundle#end()

set nocompatible
filetype on       
filetype indent on
filetype plugin on 
syntax on
set t_Co=256
set backspace=2
set expandtab
set tabstop=3 shiftwidth=2 softtabstop=2
set autoindent
set number
set guifont=JetBrains\ Mono:h14
set termguicolors
set autoread
set autowrite
autocmd! GUIEnter * set vb t_vb=
set directory=~/.vim/backups//

colorscheme gruvbox 
set background=dark

let g:gitgutter_enabled = 1

set runtimepath^=~/.vim/bundle/ctrlp.vim
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
let g:ctrlp_working_path_mode = 'rw'
let g:ctrlp_cmd = 'CtrlPMixed'
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git'

map <C-\> :NERDTreeToggle<CR>
let NERDTreeShowHidden = 1
let g:NERDTreeChDirMode = 2
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

let g:vim_jsx_pretty_colorful_config = 1

" Open vim-test results in iTerm.
let test#strategy = 'iterm'

nmap <silent> t<C-n> :TestNearest<CR>
nmap <silent> t<C-f> :TestFile<CR>
nmap <silent> t<C-s> :TestSuite<CR>
nmap <silent> t<C-l> :TestLast<CR>
nmap <silent> t<C-g> :TestVisit<CR>

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

let g:multi_cursor_use_default_mapping = 0

let g:multi_cursor_start_word_key      = '<C-n>'
let g:multi_cursor_select_all_word_key = '<A-n>'
let g:multi_cursor_start_key           = 'g<C-n>'
let g:multi_cursor_select_all_key      = 'g<A-n>'
let g:multi_cursor_next_key            = '<C-n>'
let g:multi_cursor_prev_key            = '<C-p>'
let g:multi_cursor_skip_key            = '<C-x>'
let g:multi_cursor_quit_key            = '<Esc>'

let g:auto_save = 1
let g:auto_save_events = ["CompleteDone"] 

let g:ale_linters = {
\ 'javascript': [],
\ 'typescript': ['tsserver'],
\ 'typescriptreact': ['tsserver'],
\}
let g:ale_fixers = {
\ '*': ['remove_trailing_lines', 'trim_whitespace'],
\ 'javascript': [],
\ 'typescript': ['tslint'],
\ 'typescriptreact': ['tslint'],
\}
let g:airline#extensions#ale#enabled = 1

" Highlight Fastlane as Ruby
autocmd BufNewFile,BufRead Fastfile Matchfile Appfile Gymfile Pluginfile set syntax=ruby 
